# Generated by Django 3.0.5 on 2020-04-30 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupname', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='host_idc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idcname', models.CharField(max_length=64)),
                ('idcagent', models.CharField(max_length=64)),
                ('idcaddress', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='host_manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostuser', models.CharField(max_length=64)),
                ('hostpasswd', models.CharField(max_length=64)),
                ('hostport', models.IntegerField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=32)),
                ('gid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.group')),
            ],
        ),
        migrations.CreateModel(
            name='host_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hosttype', models.CharField(max_length=64)),
                ('hostname', models.CharField(max_length=64)),
                ('hostip', models.GenericIPAddressField(db_index=True, protocol='ipv4')),
                ('hostconfig', models.CharField(max_length=64)),
                ('hostcreate_data', models.DateTimeField(auto_now_add=True)),
                ('hostupdate_data', models.DateTimeField(auto_now_add=True)),
                ('billing_idcid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.host_idc')),
                ('billing_managerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.host_manager')),
            ],
        ),
    ]
